Vagrant.require_version ">= 1.5.0", "< 1.6.0"

$agent = <<SCRIPT

source /vagrant/provision-common.sh
sudo apt-get install -y -qq puppet

SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "agent1" do |agent|
    agent.vm.provision "shell", inline: $agent, :privileged => false
    agent.vm.network :private_network, ip: "192.168.50.11"
    agent.vm.hostname = "agent"
  end

end
